remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme
collections:
  posts:
    title: The Van Gambit # Needed for Siteleaf
    output: true
    description: "A month-long experiment to see if I can keep an organized schedule and clean living space. lol." # The post list page content
    feature_text: The Van Gambit
    feature_image: assets/images/van3wide.png
